name: Frontend CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Updated to a more recent Node version
          
      - name: Install Dependencies
        run: |
          npm ci
          
      - name: Run Tests
        run: |
          npm test -- --transformIgnorePatterns "node_modules/(?!react-router|@testing-library)"
          
      - name: Build Frontend App (Port 3000)
        if: success()
        run: |
          npm run build
